/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DigitalDiary;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.*;

/**
 *
 * @author shrey
 */
public class homeGUI extends javax.swing.JFrame {
    String special;
    Date d12=new Date();
    /**
     * Creates new form homeGUI
     */
   
    public homeGUI() {
        initComponents();
        bAll.setSelected(true);
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                Date d=new Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MMMM-yyyy");
                SimpleDateFormat sdf2 = new SimpleDateFormat("hh:mm:ss aa");
                lDate.setText(sdf1.format(d));
                lTime.setText(sdf2.format(d));
            }
        }, 0, 500 );
        homeGUI.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lDate = new javax.swing.JLabel();
        lTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bNew = new javax.swing.JButton();
        fSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bImportant = new javax.swing.JToggleButton();
        bFavourite = new javax.swing.JToggleButton();
        bAll = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        bNext = new javax.swing.JButton();
        bPrevious = new javax.swing.JButton();
        dateChooser = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Diary");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lDate.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        getContentPane().add(lDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 150, 50));

        lTime.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        getContentPane().add(lTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 150, 50));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        jLabel1.setText("Digital Diary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        bNew.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bNew.setText("New Note");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });
        getContentPane().add(bNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        fSearch.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        fSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fSearchCaretUpdate(evt);
            }
        });
        getContentPane().add(fSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 500, 50));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 150, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jLabel2.setText("or");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(1050, 32767));

        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 550));
        jPanel1.add(jPanel2);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 1050, 650));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 150, -1));

        buttonGroup1.add(bImportant);
        bImportant.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bImportant.setText("Important");
        bImportant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImportantActionPerformed(evt);
            }
        });
        getContentPane().add(bImportant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 50));

        buttonGroup1.add(bFavourite);
        bFavourite.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bFavourite.setText("Favourite");
        bFavourite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFavouriteActionPerformed(evt);
            }
        });
        getContentPane().add(bFavourite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 50));

        buttonGroup1.add(bAll);
        bAll.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bAll.setText("All");
        bAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllActionPerformed(evt);
            }
        });
        getContentPane().add(bAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 150, -1));

        bNext.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bNext.setText("Next Day");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });
        getContentPane().add(bNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 150, 50));

        bPrevious.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bPrevious.setText("Previous Day");
        bPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(bPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 150, 50));

        dateChooser.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 240, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void refresh(){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
    String today=sdf.format(d);
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE link like '"+today+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
    public static void refresh(String special){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
    String today=sdf.format(d);
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE special = '"+special+"' and link like '"+today+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
    public static void refresh(Date d){
    
    SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
    String today=sdf.format(d);
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE  link like '"+today+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
    public static void refresh(String special,Date d){
    //Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
    String today=sdf.format(d);
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE special = '"+special+"' and link like '"+today+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
    
    public static void refresh(String search,boolean special){
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE Title like '"+search+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
     public static void refresh(String search,String special){
    jPanel2.removeAll();
    jPanel2.revalidate();
    jPanel2.repaint();
    int count=0;
    try(Connection con=mysqlConnect.connection("root", "shrey"); 
            Statement stmt = con.createStatement();){
        String query2="SELECT link FROM `Scribble` WHERE special = '"+special+"' and Title like '"+search+"%'";
        ResultSet rs2=stmt.executeQuery(query2);
        while(rs2.next()){
        if(count%3==0 && count!=0){
            Dimension dim=new Dimension(1050,jPanel2.getPreferredSize().height+510);
            jPanel2.setPreferredSize(dim);
        }
        jPanel2.add(new NoteCard(rs2.getString("link")));
        count++;
        }
    stmt.close();
    con.close();
    }
    catch(Exception e){}
   
    }
    
    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        new NotepadGUI("Add Note").setVisible(true);
    }//GEN-LAST:event_bNewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Date d1=new Date(dateChooser.getDate().getYear()-1900,dateChooser.getDate().getMonthValue()-1,dateChooser.getDate().getDayOfMonth());
      if(bImportant.isSelected() || bFavourite.isSelected()){refresh(special,d1);}
      else refresh(d1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bImportantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImportantActionPerformed
        refresh("Important",d12); 
        special="Important";// TODO add your handling code here:
    }//GEN-LAST:event_bImportantActionPerformed

    private void bFavouriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFavouriteActionPerformed
     refresh("Favourite",d12);  
     special="Favourite";// TODO add your handling code here:
    }//GEN-LAST:event_bFavouriteActionPerformed

    private void bAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllActionPerformed
     refresh(); 
     // TODO add your handling code here:
    }//GEN-LAST:event_bAllActionPerformed

    private void fSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fSearchCaretUpdate
     if(bImportant.isSelected() || bFavourite.isSelected()){refresh(fSearch.getText().trim(),special);}
        else if("".equals(fSearch.getText()))refresh();
     else refresh(fSearch.getText().trim(),true);   // TODO add your handling code here:
    }//GEN-LAST:event_fSearchCaretUpdate

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        d12.setDate(d12.getDate()+1);
        if(bImportant.isSelected() || bFavourite.isSelected()){refresh(special,d12);}
        else refresh(d12);
      
    }//GEN-LAST:event_bNextActionPerformed

    private void bPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPreviousActionPerformed
        d12.setDate(d12.getDate()-1);
        if(bImportant.isSelected() || bFavourite.isSelected()){refresh(special,d12);}
        else refresh(d12);
       // TODO add your handling code here:
    }//GEN-LAST:event_bPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              homeGUI h=  new homeGUI();
                      h.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bAll;
    private javax.swing.JToggleButton bFavourite;
    private javax.swing.JToggleButton bImportant;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.github.lgooddatepicker.components.DatePicker dateChooser;
    private javax.swing.JTextField fSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lTime;
    // End of variables declaration//GEN-END:variables
}
