package DigitalDiary;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shrey
 */
public class NoteCard extends javax.swing.JPanel {
    String name;
    /**
     * Creates new form NoteCard
     * @param name
     */
    public NoteCard(String name) {
        initComponents();
        this.name=name;
        jPanel1.setVisible(false);
        try(BufferedReader br = new BufferedReader(new FileReader(name))){
        StringBuilder sb=new StringBuilder();
        String line = br.readLine();
        while(line!=null){
        sb.append(line);
        sb.append(System.lineSeparator());
        line=br.readLine();
        }
        String note=sb.toString();
        cardNotes.setText(note);
        }
        catch(FileNotFoundException e){
        System.out.println(e.getMessage());
        } 
        catch (IOException ex) {
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardNotes = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseEntered(evt);
            }
        });

        cardNotes.setEditable(false);
        cardNotes.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        cardNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardNotesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardNotesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(cardNotes);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bEdit.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bEdit.setText("EDIT");
        bEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEditMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditMouseEntered(evt);
            }
        });
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel1.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        bDelete.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        bDelete.setText("DELETE");
        bDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDeleteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bDeleteMouseEntered(evt);
            }
        });
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 170, 50));

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 340, 50));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
      //  jPanel1.setVisible(true);
             // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
    //  jPanel1.setVisible(false);
             // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

    private void jScrollPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseEntered
  //    jPanel1.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseEntered

    private void cardNotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardNotesMouseEntered
  //    jPanel1.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_cardNotesMouseEntered

    private void jScrollPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseExited
   //  jPanel1.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseExited

    private void cardNotesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardNotesMouseExited
    // jPanel1.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_cardNotesMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
      jPanel1.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
jPanel1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void bDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDeleteMouseEntered
      jPanel1.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_bDeleteMouseEntered

    private void bDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDeleteMouseExited
 jPanel1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bDeleteMouseExited

    private void bEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseEntered
 jPanel1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bEditMouseEntered

    private void bEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseExited
 jPanel1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bEditMouseExited

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
     new NotepadGUI("Edit Note",name).setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_bEditActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
      try(Connection con=mysqlConnect.connection("root", "shrey");Statement stmt=con.createStatement();){
      String query = "DELETE FROM `Scribble` WHERE Link = '"+name+"';";
      stmt.executeUpdate(query);
      homeGUI.refresh();}
      catch(Exception e){
      System.out.println(name);
      }// TODO add your handling code here:
    }//GEN-LAST:event_bDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JTextPane cardNotes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
